Host = "https://imagvfx.com"
LeafEntryType = "part"
Scene = "${SHOW_ROOT}/${SHOW}/${CATEG}/${GROUP}/${UNIT}/part/${PART}/${GROUP}_${UNIT}_${PART}_${ELEM}_${VER}.${EXT}"

Envs = [
	"SHOW_ROOT=/Users/kybin/show",
	"NEW_VER=v001",
]

[Dir]
show = "${SHOW_ROOT}/${SHOW}"
category = "${SHOW_ROOT}/${SHOW}/${CATEG}"
group = "${SHOW_ROOT}/${SHOW}/${CATEG}/${GROUP}"
shot = "${SHOW_ROOT}/${SHOW}/${CATEG}/${GROUP}/${UNIT}"
asset = "${SHOW_ROOT}/${SHOW}/${CATEG}/${GROUP}/${UNIT}"
part = "${SHOW_ROOT}/${SHOW}/${CATEG}/${GROUP}/${UNIT}/part/${PART}"

[[Programs]]
Name = "Blender"
Ext = "blend"
Create = "Blender"
Open = "Blender"

