// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SessionUser() {
  return window['go']['main']['App']['SessionUser']();
}

export function WaitLogin(arg1) {
  return window['go']['main']['App']['WaitLogin'](arg1);
}

export function AddProgramInUse(arg1, arg2) {
  return window['go']['main']['App']['AddProgramInUse'](arg1, arg2);
}

export function CurrentPath() {
  return window['go']['main']['App']['CurrentPath']();
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Programs() {
  return window['go']['main']['App']['Programs']();
}

export function OpenLoginPage(arg1) {
  return window['go']['main']['App']['OpenLoginPage'](arg1);
}

export function ClearEntries() {
  window['go']['main']['App']['ClearEntries']();
}

export function EntryEnvirons(arg1) {
  return window['go']['main']['App']['EntryEnvirons'](arg1);
}

export function GoBack() {
  return window['go']['main']['App']['GoBack']();
}

export function GoTo(arg1) {
  window['go']['main']['App']['GoTo'](arg1);
}

export function GoForward() {
  return window['go']['main']['App']['GoForward']();
}

export function Logout() {
  window['go']['main']['App']['Logout']();
}

export function NewElement(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewElement'](arg1, arg2, arg3);
}

export function SetAssignedOnly(arg1) {
  window['go']['main']['App']['SetAssignedOnly'](arg1);
}

export function IsLeaf(arg1) {
  return window['go']['main']['App']['IsLeaf'](arg1);
}

export function ListEntries() {
  return window['go']['main']['App']['ListEntries']();
}

export function ProgramsInUse() {
  return window['go']['main']['App']['ProgramsInUse']();
}

export function RemoveProgramInUse(arg1) {
  return window['go']['main']['App']['RemoveProgramInUse'](arg1);
}
